### ISSUE TITLE
Dash

### ISSUE THREAD

**Issue by Ronogamer7771** [mahtab2003/Xera#51]
Hi!
I uploaded xera client area for the first time on one host but I have setup xera multiple times and I have never gotten this error

I make admin account but dashboard says this

An Error Was Encountered
Unable to load the requested file: page/includes/admin/header.php

**Comment by roshan1885** [comment]
You didn't upload all the files

**Comment by 4yx** [comment]
> An Error Was Encountered Unable to load the requested file: page/includes/admin/header.php

Does it say that in the main page? Can you share a screenshot?
Additionally, like @OnionDev1885 mentioned, could you check if the file exists?

Are you using the latest version from dev, or the release version? If it's the release version please try using the [latest development version](https://github.com/mahtab2003/Xera/archive/refs/heads/dev.zip) and see if the issue persists.

**Comment by Ronogamer7771** [comment]
> You didn't upload all the files

i did

**Comment by greenreader9** [comment]
Try doing it again. The error means the file was not uploaded correctly

**Comment by 4yx** [comment]
> i did

Are you using the latest version from dev, or the release version?

**Comment by tanguy-fgl** [comment]
I had also this error. It's due to the new template system I will work tomorrow on a patch

**Comment by tanguy-fgl** [comment]
I don't remember how I fixed that so it will takes time

**Comment by 4yx** [comment]
> I had also this error. It's due to the new template system 

A quick search I did doesn't seem to confirm this, primarily because everything that requests the header is written as ``$this->base->get_template().'/page/includes/admin/header`` which seems to be correct (and it works in my local installation, but that's irrelevant). I won't bet on it though; VSCode's search might be missing something.

@Ronogamer7771 can you confirm you're on the latest development version? Share a URL perhaps, if it is not sensitive?

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
