### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by EasyTechniques** [mahtab2003/Xera#61]
When I go to login on xera admin, it say that Invalid email address or password. Though i entered email and password correctly can anyone give me a solution plz?

**Comment by 4yx** [comment]
> When I go to login on xera admin, it say that Invalid email address or password. Though i entered email and password correctly can anyone give me a solution plz?

Strange. You are trying to login to the admin area (url/a/login or url/index.php/a/login) and not the client area (which has a ``u`` where the a is), correct? You should be seeing something like this screen (although not in dark mode, that's because I have a ready installation):
![How it should show](https://i.imgur.com/369sTdR.png)

If that's the case and you're still unable to login, check your database's ``is_admin`` table. Does your account with the email you're trying to use appear there?

**Comment by EasyTechniques** [comment]
Thanks. Now i can login on dashboard
