### ISSUE TITLE
When I try to create a hosting account, it gets stuck at ''Check domain''

### ISSUE THREAD

**Issue by flooydorg** [mahtab2003/Xera#73]
I installed the current version of Xera, and when I access the link, it leaves me stuck on the page, without redirecting me to another one.

**Comment by modearsd** [comment]
Add HCaptcha & Google Recaptcha support (Bots will not create accounts)
Add an option to choose what Captcha we want to use (or if we don't)
Add a language file (all messages will be in this file, it's better for other people who speak an other language like me (french) to translate at every update. Maybe in a .json file)
Detect the browser language to display Mofhy in the right language (only if a respective file is created otherwise it displays Mofhy in English)
Integrate IFastNet or other domain resseller
Integrate Google Analytics (option in admin settings to set the GA Id)
Writte a Privacy Policy (cookies used by Mofhy) & a Terms Of Use text (integrate IFastNet and GoGetSSL terms of use in Mofhy. It's better for the security of the enterprise who use Mofhy)
Update checker
Seo options to set the description, the name of the website, the favicon & more...
Add Site.pro integration
Add external auth like Discord, Google, Facebook
Add an option in the admin panel to set if Mofhy will use only classic login & signup forms or external auth or the both
Add an option to set the <div> for ads in the admin panel instead of editing all pages

**Comment by modearsd** [comment]
Add HCaptcha & Google Recaptcha support (Bots will not create accounts)
Add an option to choose what Captcha we want to use (or if we don't)
Add a language file (all messages will be in this file, it's better for other people who speak an other language like me (french) to translate at every update. Maybe in a .json file)
Detect the browser language to display in the right language (only if a respective file is created otherwise it displays in English)
Integrate IFastNet or other domain resseller
Integrate Google Analytics (option in admin settings to set the GA Id)
Writte a Privacy Policy (cookies used by ) & a Terms Of Use text (integrate IFastNet and GoGetSSL terms of use in . It's better for the security of the enterprise who use )
Update checker
Seo options to set the description, the name of the website, the favicon & more...
Add Site.pro integration
Add external auth like Discord, Google, Facebook
Add an option in the admin panel to set if will use only classic login & signup forms or external auth or the both
Add an option to set the <div> for ads in the admin panel instead of editing all pages

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
